### ISSUE TITLE
kubedns部署那一步说明太少了，还有一个错误

### ISSUE THREAD

**Issue by aimahou** [greatbsky/KubernetesDoc#1]
您好，按着您的文章配置k8s，遇到一些问题，提一下，感谢分享。
1.docker images里的镜像应该提前docker pull下来比较好；
2.应该编辑/etc/kubernetes/apiserver修改
KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"     将“ServiceAccount,”删除，否则后面执行
kubectl create -f kubedns-controller.yaml.sed
kubectl create -f kubedns-svc.yaml.sed
tail -f /var/log/messages
这三步后，会报错，“pods "kube-dns-870655637-" is forbidden: service account kube-system/kube-dns was not found, retry after the service account is created”
3.按您这篇文章没办法配置成功，其中ETCD和docker我都是自己重新配置的。

**Comment by greatbsky** [comment]
谢谢反馈！
1. 先pull下来是有好处，但网络没问题也无大碍。
2. ServiceAccount 貌似是不应该被删除的，有群友删除后还出其他问题，改回来才行的。

此文档是v1.5.2的，里面的一些文件链接当时是新的，现在有些已经做过修改，也不打算一直更新这个版本的文档了。后期发布新版本时考虑再发布个新版的文档。
